---
- name: Create Jenkins Namespace
  hosts: localhost
  tasks:
    - name: Create Kubernetes Namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: jenkins
        state: present
