---
- name: Deploy Jenkins on Kubernetes
  hosts: localhost
  tasks:
    - name: Apply Namespace
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'ansible/namespace.yaml') }}"

    - name: Apply Service Account and Cluster Role Binding
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'ansible/service_account_and_cluster_role_binding.yaml') }}"

    - name: Apply Persistent Volume Claim
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'ansible/persistent_volume_claim.yaml') }}"

    - name: Apply Jenkins Deployment
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'ansible/jenkins_deployment.yaml') }}"

    - name: Apply Jenkins Service
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('file', 'ansible/jenkins_service.yaml') }}"
