---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer 

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-agents
  namespace: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - port: 50000
      targetPort: 50000
  type: LoadBalancer 
