apiVersion: v1
kind: Secret
metadata:
  name: docker-config 
  namespace: jenkins
type: Opaque
data:
  config.json: ew0KICAgICJhdXRocyI6IHsNCiAgICAgICAgImh0dHBzOi8vaW5kZXguZG9ja2VyLmlvL3YxLyI6IHsNCiAgICAgICAgICAgICJhdXRoIjogIllXaGhibTV2Y21FME5EQTZRV1J0YVc1QVJFOURTMFZTIg0KICAgICAgICB9DQogICAgfQ0KfQ==